# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/admin/repo/Zybo-Z7-20-pcam-5c-26oct/src/bd/system/ip/system_video_dynclk_1/system_video_dynclk_1.xci
# IP: The module: 'system_video_dynclk_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/admin/repo/Zybo-Z7-20-pcam-5c-26oct/src/bd/system/ip/system_video_dynclk_1/system_video_dynclk_1_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_video_dynclk_1'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/admin/repo/Zybo-Z7-20-pcam-5c-26oct/src/bd/system/ip/system_video_dynclk_1/system_video_dynclk_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_video_dynclk_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/admin/repo/Zybo-Z7-20-pcam-5c-26oct/src/bd/system/ip/system_video_dynclk_1/system_video_dynclk_1_late.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_video_dynclk_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/admin/repo/Zybo-Z7-20-pcam-5c-26oct/src/bd/system/ip/system_video_dynclk_1/system_video_dynclk_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_video_dynclk_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: C:/Users/admin/repo/Zybo-Z7-20-pcam-5c-26oct/src/bd/system/ip/system_video_dynclk_1/system_video_dynclk_1.xci
# IP: The module: 'system_video_dynclk_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/admin/repo/Zybo-Z7-20-pcam-5c-26oct/src/bd/system/ip/system_video_dynclk_1/system_video_dynclk_1_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_video_dynclk_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/admin/repo/Zybo-Z7-20-pcam-5c-26oct/src/bd/system/ip/system_video_dynclk_1/system_video_dynclk_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_video_dynclk_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/admin/repo/Zybo-Z7-20-pcam-5c-26oct/src/bd/system/ip/system_video_dynclk_1/system_video_dynclk_1_late.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_video_dynclk_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/admin/repo/Zybo-Z7-20-pcam-5c-26oct/src/bd/system/ip/system_video_dynclk_1/system_video_dynclk_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_video_dynclk_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
