#!/bin/bash -f
#*********************************************************************************************************
# Vivado (TM) v2017.4 (64-bit)
#
# Filename    : system.sh
# Simulator   : Synopsys Verilog Compiler Simulator
# Description : Simulation script for compiling, elaborating and verifying the project source files.
#               The script will automatically create the design libraries sub-directories in the run
#               directory, add the library logical mappings in the simulator setup file, create default
#               'do/prj' file, execute compilation, elaboration and simulation steps.
#
# Generated by Vivado on Thu Apr 04 23:28:22 +0300 2019
# SW Build 2086221 on Fri Dec 15 20:55:39 MST 2017
#
# Copyright 1986-2017 Xilinx, Inc. All Rights Reserved. 
#
# usage: system.sh [-help]
# usage: system.sh [-lib_map_path]
# usage: system.sh [-noclean_files]
# usage: system.sh [-reset_run]
#
# Prerequisite:- To compile and run simulation, you must compile the Xilinx simulation libraries using the
# 'compile_simlib' TCL command. For more information about this command, run 'compile_simlib -help' in the
# Vivado Tcl Shell. Once the libraries have been compiled successfully, specify the -lib_map_path switch
# that points to these libraries and rerun export_simulation. For more information about this switch please
# type 'export_simulation -help' in the Tcl shell.
#
# You can also point to the simulation libraries by either replacing the <SPECIFY_COMPILED_LIB_PATH> in this
# script with the compiled library directory path or specify this path with the '-lib_map_path' switch when
# executing this script. Please type 'system.sh -help' for more information.
#
# Additional references - 'Xilinx Vivado Design Suite User Guide:Logic simulation (UG900)'
#
#*********************************************************************************************************

# Directory path for design sources and include directories (if any) wrt this path
ref_dir="."

# Override directory with 'export_sim_ref_dir' env path value if set in the shell
if [[ (! -z "$export_sim_ref_dir") && ($export_sim_ref_dir != "") ]]; then
  ref_dir="$export_sim_ref_dir"
fi

# Command line options
vlogan_opts="-full64"
vhdlan_opts="-full64"
vcs_elab_opts="-full64 -debug_pp -t ps -licqueue -l elaborate.log"
vcs_sim_opts="-ucli -licqueue -l simulate.log"

# Design libraries
design_libs=(xil_defaultlib xpm lib_cdc_v1_0_2 lib_pkg_v1_0_2 fifo_generator_v13_2_1 lib_fifo_v1_0_10 blk_mem_gen_v8_4_1 lib_bmg_v1_0_10 lib_srl_fifo_v1_0_2 axi_datamover_v5_1_17 axi_vdma_v6_3_3 axi_infrastructure_v1_1_0 smartconnect_v1_0 axi_protocol_checker_v2_0_1 axi_vip_v1_1_1 processing_system7_vip_v1_0_3 proc_sys_reset_v5_0_12 axi_lite_ipif_v3_0_4 v_tc_v6_1_12 v_vid_in_axi4s_v4_0_7 v_axi4s_vid_out_v4_0_8 xlconcat_v2_1_1 generic_baseblocks_v2_1_0 axi_register_slice_v2_1_15 axi_data_fifo_v2_1_14 axi_crossbar_v2_1_16 axis_infrastructure_v1_1_0 axis_data_fifo_v1_1_16 axi_protocol_converter_v2_1_15)

# Simulation root library directory
sim_lib_dir="vcs_lib"

# Script info
echo -e "system.sh - Script generated by export_simulation (Vivado v2017.4 (64-bit)-id)\n"

# Main steps
run()
{
  check_args $# $1
  setup $1 $2
  compile
  elaborate
  simulate
}

# RUN_STEP: <compile>
compile()
{
  # Compile design files
  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../../src/bd/system/ipshared/f8d8/hdl" +incdir+"$ref_dir/../../../../../src/bd/system/ipshared/4868" +incdir+"$ref_dir/../../../../../src/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../../src/bd/system/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../../../src/bd/system/ipshared/1313/hdl" +incdir+"$ref_dir/../../../../../src/bd/system/ip/system_MIPI_CSI_2_RX_0_0_1/hdl/line_buffer/hdl" +incdir+"$ref_dir/../../../../../src/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_rxclk/hdl/verilog" +incdir+"$ref_dir/../../../../../src/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_refclk/hdl/verilog" +incdir+"$ref_dir/../../../../../src/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_scnn_refclk/hdl/verilog" +incdir+"$ref_dir/../../../../../src/bd/system/ip/system_MIPI_CSI_2_RX_0_0_1/hdl/ila_rxclk_lane/hdl/verilog" +incdir+"$ref_dir/../../../../../src/bd/system/ip/system_MIPI_CSI_2_RX_0_0_1/hdl/ila_rxclk/hdl/verilog" +incdir+"$ref_dir/../../../../../src/bd/system/ip/system_MIPI_CSI_2_RX_0_0_1/hdl/ila_vidclk/hdl/verilog" +incdir+"D:/Kits/Ti/beaglebone/Xilinx/Vivado/2017.4/data/xilinx_vip/include" \
    "D:/Kits/Ti/beaglebone/Xilinx/Vivado/2017.4/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv" \
    "D:/Kits/Ti/beaglebone/Xilinx/Vivado/2017.4/data/ip/xpm/xpm_fifo/hdl/xpm_fifo.sv" \
    "D:/Kits/Ti/beaglebone/Xilinx/Vivado/2017.4/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xpm $vhdlan_opts \
    "D:/Kits/Ti/beaglebone/Xilinx/Vivado/2017.4/data/ip/xpm/xpm_VCOMP.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/system/ipshared/40b8/hdl/LineBuffer.vhd" \
    "$ref_dir/../../../bd/system/ipshared/40b8/hdl/AXI_BayerToRGB.vhd" \
    "$ref_dir/../../../bd/system/ip/system_AXI_BayerToRGB_1_0/sim/system_AXI_BayerToRGB_1_0.vhd" \
    "$ref_dir/../../../bd/system/ipshared/2846/hdl/StoredGammaCoefs.vhd" \
    "$ref_dir/../../../bd/system/ipshared/2846/hdl/AXI_GammaCorrection.vhd" \
    "$ref_dir/../../../bd/system/ip/system_AXI_GammaCorrection_0_0/sim/system_AXI_GammaCorrection_0_0.vhd" \
    "$ref_dir/../../../bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_rxclk/sim/ila_sfen_rxclk.vhd" \
    "$ref_dir/../../../bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_refclk/sim/ila_sfen_refclk.vhd" \
    "$ref_dir/../../../bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_scnn_refclk/sim/ila_scnn_refclk.vhd" \
    "$ref_dir/../../../bd/system/ipshared/ead7/hdl/SyncAsync.vhd" \
    "$ref_dir/../../../bd/system/ipshared/ead7/hdl/DPHY_Pkg.vhd" \
    "$ref_dir/../../../bd/system/ipshared/ead7/hdl/SyncAsyncReset.vhd" \
    "$ref_dir/../../../bd/system/ipshared/ead7/hdl/DebugLib.vhd" \
    "$ref_dir/../../../bd/system/ipshared/ead7/hdl/HS_Deserializer.vhd" \
    "$ref_dir/../../../bd/system/ipshared/ead7/hdl/GlitchFilter.vhd" \
    "$ref_dir/../../../bd/system/ipshared/ead7/hdl/HS_Clocking.vhd" \
    "$ref_dir/../../../bd/system/ipshared/ead7/hdl/InputBuffer.vhd" \
    "$ref_dir/../../../bd/system/ipshared/ead7/hdl/DPHY_LaneSFEN.vhd" \
    "$ref_dir/../../../bd/system/ipshared/ead7/hdl/DPHY_LaneSCNN.vhd" \
    "$ref_dir/../../../bd/system/ipshared/ead7/hdl/S_AXI_Lite.vhd" \
    "$ref_dir/../../../bd/system/ipshared/ead7/hdl/MIPI_DPHY_Receiver.vhd" \
    "$ref_dir/../../../bd/system/ip/system_MIPI_D_PHY_RX_0_0/sim/system_MIPI_D_PHY_RX_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work lib_cdc_v1_0_2 $vhdlan_opts \
    "$ref_dir/../../../../../src/bd/system/ipshared/ef1e/hdl/lib_cdc_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work lib_pkg_v1_0_2 $vhdlan_opts \
    "$ref_dir/../../../../../src/bd/system/ipshared/0513/hdl/lib_pkg_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work fifo_generator_v13_2_1 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../../src/bd/system/ipshared/f8d8/hdl" +incdir+"$ref_dir/../../../../../src/bd/system/ipshared/4868" +incdir+"$ref_dir/../../../../../src/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../../src/bd/system/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../../../src/bd/system/ipshared/1313/hdl" +incdir+"$ref_dir/../../../../../src/bd/system/ip/system_MIPI_CSI_2_RX_0_0_1/hdl/line_buffer/hdl" +incdir+"$ref_dir/../../../../../src/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_rxclk/hdl/verilog" +incdir+"$ref_dir/../../../../../src/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_refclk/hdl/verilog" +incdir+"$ref_dir/../../../../../src/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_scnn_refclk/hdl/verilog" +incdir+"$ref_dir/../../../../../src/bd/system/ip/system_MIPI_CSI_2_RX_0_0_1/hdl/ila_rxclk_lane/hdl/verilog" +incdir+"$ref_dir/../../../../../src/bd/system/ip/system_MIPI_CSI_2_RX_0_0_1/hdl/ila_rxclk/hdl/verilog" +incdir+"$ref_dir/../../../../../src/bd/system/ip/system_MIPI_CSI_2_RX_0_0_1/hdl/ila_vidclk/hdl/verilog" +incdir+"D:/Kits/Ti/beaglebone/Xilinx/Vivado/2017.4/data/xilinx_vip/include" \
    "$ref_dir/../../../../../src/bd/system/ipshared/5c35/simulation/fifo_generator_vlog_beh.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work fifo_generator_v13_2_1 $vhdlan_opts \
    "$ref_dir/../../../../../src/bd/system/ipshared/5c35/hdl/fifo_generator_v13_2_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work fifo_generator_v13_2_1 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../../src/bd/system/ipshared/f8d8/hdl" +incdir+"$ref_dir/../../../../../src/bd/system/ipshared/4868" +incdir+"$ref_dir/../../../../../src/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../../src/bd/system/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../../../src/bd/system/ipshared/1313/hdl" +incdir+"$ref_dir/../../../../../src/bd/system/ip/system_MIPI_CSI_2_RX_0_0_1/hdl/line_buffer/hdl" +incdir+"$ref_dir/../../../../../src/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_rxclk/hdl/verilog" +incdir+"$ref_dir/../../../../../src/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_refclk/hdl/verilog" +incdir+"$ref_dir/../../../../../src/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_scnn_refclk/hdl/verilog" +incdir+"$ref_dir/../../../../../src/bd/system/ip/system_MIPI_CSI_2_RX_0_0_1/hdl/ila_rxclk_lane/hdl/verilog" +incdir+"$ref_dir/../../../../../src/bd/system/ip/system_MIPI_CSI_2_RX_0_0_1/hdl/ila_rxclk/hdl/verilog" +incdir+"$ref_dir/../../../../../src/bd/system/ip/system_MIPI_CSI_2_RX_0_0_1/hdl/ila_vidclk/hdl/verilog" +incdir+"D:/Kits/Ti/beaglebone/Xilinx/Vivado/2017.4/data/xilinx_vip/include" \
    "$ref_dir/../../../../../src/bd/system/ipshared/5c35/hdl/fifo_generator_v13_2_rfs.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work lib_fifo_v1_0_10 $vhdlan_opts \
    "$ref_dir/../../../../../src/bd/system/ipshared/f10a/hdl/lib_fifo_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work blk_mem_gen_v8_4_1 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../../src/bd/system/ipshared/f8d8/hdl" +incdir+"$ref_dir/../../../../../src/bd/system/ipshared/4868" +incdir+"$ref_dir/../../../../../src/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../../src/bd/system/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../../../src/bd/system/ipshared/1313/hdl" +incdir+"$ref_dir/../../../../../src/bd/system/ip/system_MIPI_CSI_2_RX_0_0_1/hdl/line_buffer/hdl" +incdir+"$ref_dir/../../../../../src/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_rxclk/hdl/verilog" +incdir+"$ref_dir/../../../../../src/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_refclk/hdl/verilog" +incdir+"$ref_dir/../../../../../src/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_scnn_refclk/hdl/verilog" +incdir+"$ref_dir/../../../../../src/bd/system/ip/system_MIPI_CSI_2_RX_0_0_1/hdl/ila_rxclk_lane/hdl/verilog" +incdir+"$ref_dir/../../../../../src/bd/system/ip/system_MIPI_CSI_2_RX_0_0_1/hdl/ila_rxclk/hdl/verilog" +incdir+"$ref_dir/../../../../../src/bd/system/ip/system_MIPI_CSI_2_RX_0_0_1/hdl/ila_vidclk/hdl/verilog" +incdir+"D:/Kits/Ti/beaglebone/Xilinx/Vivado/2017.4/data/xilinx_vip/include" \
    "$ref_dir/../../../../../src/bd/system/ipshared/67d8/simulation/blk_mem_gen_v8_4.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work lib_bmg_v1_0_10 $vhdlan_opts \
    "$ref_dir/../../../../../src/bd/system/ipshared/9340/hdl/lib_bmg_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work lib_srl_fifo_v1_0_2 $vhdlan_opts \
    "$ref_dir/../../../../../src/bd/system/ipshared/51ce/hdl/lib_srl_fifo_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_datamover_v5_1_17 $vhdlan_opts \
    "$ref_dir/../../../../../src/bd/system/ipshared/71f3/hdl/axi_datamover_v5_1_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work axi_vdma_v6_3_3 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../../src/bd/system/ipshared/f8d8/hdl" +incdir+"$ref_dir/../../../../../src/bd/system/ipshared/4868" +incdir+"$ref_dir/../../../../../src/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../../src/bd/system/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../../../src/bd/system/ipshared/1313/hdl" +incdir+"$ref_dir/../../../../../src/bd/system/ip/system_MIPI_CSI_2_RX_0_0_1/hdl/line_buffer/hdl" +incdir+"$ref_dir/../../../../../src/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_rxclk/hdl/verilog" +incdir+"$ref_dir/../../../../../src/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_refclk/hdl/verilog" +incdir+"$ref_dir/../../../../../src/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_scnn_refclk/hdl/verilog" +incdir+"$ref_dir/../../../../../src/bd/system/ip/system_MIPI_CSI_2_RX_0_0_1/hdl/ila_rxclk_lane/hdl/verilog" +incdir+"$ref_dir/../../../../../src/bd/system/ip/system_MIPI_CSI_2_RX_0_0_1/hdl/ila_rxclk/hdl/verilog" +incdir+"$ref_dir/../../../../../src/bd/system/ip/system_MIPI_CSI_2_RX_0_0_1/hdl/ila_vidclk/hdl/verilog" +incdir+"D:/Kits/Ti/beaglebone/Xilinx/Vivado/2017.4/data/xilinx_vip/include" \
    "$ref_dir/../../../../../src/bd/system/ipshared/f8d8/hdl/axi_vdma_v6_3_rfs.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work axi_vdma_v6_3_3 $vhdlan_opts \
    "$ref_dir/../../../../../src/bd/system/ipshared/f8d8/hdl/axi_vdma_v6_3_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/system/ip/system_axi_vdma_0_0/sim/system_axi_vdma_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../../src/bd/system/ipshared/f8d8/hdl" +incdir+"$ref_dir/../../../../../src/bd/system/ipshared/4868" +incdir+"$ref_dir/../../../../../src/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../../src/bd/system/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../../../src/bd/system/ipshared/1313/hdl" +incdir+"$ref_dir/../../../../../src/bd/system/ip/system_MIPI_CSI_2_RX_0_0_1/hdl/line_buffer/hdl" +incdir+"$ref_dir/../../../../../src/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_rxclk/hdl/verilog" +incdir+"$ref_dir/../../../../../src/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_refclk/hdl/verilog" +incdir+"$ref_dir/../../../../../src/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_scnn_refclk/hdl/verilog" +incdir+"$ref_dir/../../../../../src/bd/system/ip/system_MIPI_CSI_2_RX_0_0_1/hdl/ila_rxclk_lane/hdl/verilog" +incdir+"$ref_dir/../../../../../src/bd/system/ip/system_MIPI_CSI_2_RX_0_0_1/hdl/ila_rxclk/hdl/verilog" +incdir+"$ref_dir/../../../../../src/bd/system/ip/system_MIPI_CSI_2_RX_0_0_1/hdl/ila_vidclk/hdl/verilog" +incdir+"D:/Kits/Ti/beaglebone/Xilinx/Vivado/2017.4/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/system/ip/system_clk_wiz_0_0/system_clk_wiz_0_0_clk_wiz.v" \
    "$ref_dir/../../../bd/system/ip/system_clk_wiz_0_0/system_clk_wiz_0_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_infrastructure_v1_1_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../../src/bd/system/ipshared/f8d8/hdl" +incdir+"$ref_dir/../../../../../src/bd/system/ipshared/4868" +incdir+"$ref_dir/../../../../../src/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../../src/bd/system/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../../../src/bd/system/ipshared/1313/hdl" +incdir+"$ref_dir/../../../../../src/bd/system/ip/system_MIPI_CSI_2_RX_0_0_1/hdl/line_buffer/hdl" +incdir+"$ref_dir/../../../../../src/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_rxclk/hdl/verilog" +incdir+"$ref_dir/../../../../../src/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_refclk/hdl/verilog" +incdir+"$ref_dir/../../../../../src/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_scnn_refclk/hdl/verilog" +incdir+"$ref_dir/../../../../../src/bd/system/ip/system_MIPI_CSI_2_RX_0_0_1/hdl/ila_rxclk_lane/hdl/verilog" +incdir+"$ref_dir/../../../../../src/bd/system/ip/system_MIPI_CSI_2_RX_0_0_1/hdl/ila_rxclk/hdl/verilog" +incdir+"$ref_dir/../../../../../src/bd/system/ip/system_MIPI_CSI_2_RX_0_0_1/hdl/ila_vidclk/hdl/verilog" +incdir+"D:/Kits/Ti/beaglebone/Xilinx/Vivado/2017.4/data/xilinx_vip/include" \
    "$ref_dir/../../../../../src/bd/system/ipshared/ec67/hdl/axi_infrastructure_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../../src/bd/system/ipshared/f8d8/hdl" +incdir+"$ref_dir/../../../../../src/bd/system/ipshared/4868" +incdir+"$ref_dir/../../../../../src/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../../src/bd/system/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../../../src/bd/system/ipshared/1313/hdl" +incdir+"$ref_dir/../../../../../src/bd/system/ip/system_MIPI_CSI_2_RX_0_0_1/hdl/line_buffer/hdl" +incdir+"$ref_dir/../../../../../src/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_rxclk/hdl/verilog" +incdir+"$ref_dir/../../../../../src/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_refclk/hdl/verilog" +incdir+"$ref_dir/../../../../../src/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_scnn_refclk/hdl/verilog" +incdir+"$ref_dir/../../../../../src/bd/system/ip/system_MIPI_CSI_2_RX_0_0_1/hdl/ila_rxclk_lane/hdl/verilog" +incdir+"$ref_dir/../../../../../src/bd/system/ip/system_MIPI_CSI_2_RX_0_0_1/hdl/ila_rxclk/hdl/verilog" +incdir+"$ref_dir/../../../../../src/bd/system/ip/system_MIPI_CSI_2_RX_0_0_1/hdl/ila_vidclk/hdl/verilog" +incdir+"D:/Kits/Ti/beaglebone/Xilinx/Vivado/2017.4/data/xilinx_vip/include" \
    "$ref_dir/../../../../../src/bd/system/ipshared/02c8/hdl/sc_util_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_protocol_checker_v2_0_1 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../../src/bd/system/ipshared/f8d8/hdl" +incdir+"$ref_dir/../../../../../src/bd/system/ipshared/4868" +incdir+"$ref_dir/../../../../../src/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../../src/bd/system/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../../../src/bd/system/ipshared/1313/hdl" +incdir+"$ref_dir/../../../../../src/bd/system/ip/system_MIPI_CSI_2_RX_0_0_1/hdl/line_buffer/hdl" +incdir+"$ref_dir/../../../../../src/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_rxclk/hdl/verilog" +incdir+"$ref_dir/../../../../../src/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_refclk/hdl/verilog" +incdir+"$ref_dir/../../../../../src/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_scnn_refclk/hdl/verilog" +incdir+"$ref_dir/../../../../../src/bd/system/ip/system_MIPI_CSI_2_RX_0_0_1/hdl/ila_rxclk_lane/hdl/verilog" +incdir+"$ref_dir/../../../../../src/bd/system/ip/system_MIPI_CSI_2_RX_0_0_1/hdl/ila_rxclk/hdl/verilog" +incdir+"$ref_dir/../../../../../src/bd/system/ip/system_MIPI_CSI_2_RX_0_0_1/hdl/ila_vidclk/hdl/verilog" +incdir+"D:/Kits/Ti/beaglebone/Xilinx/Vivado/2017.4/data/xilinx_vip/include" \
    "$ref_dir/../../../../../src/bd/system/ipshared/3b24/hdl/axi_protocol_checker_v2_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_vip_v1_1_1 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../../src/bd/system/ipshared/f8d8/hdl" +incdir+"$ref_dir/../../../../../src/bd/system/ipshared/4868" +incdir+"$ref_dir/../../../../../src/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../../src/bd/system/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../../../src/bd/system/ipshared/1313/hdl" +incdir+"$ref_dir/../../../../../src/bd/system/ip/system_MIPI_CSI_2_RX_0_0_1/hdl/line_buffer/hdl" +incdir+"$ref_dir/../../../../../src/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_rxclk/hdl/verilog" +incdir+"$ref_dir/../../../../../src/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_refclk/hdl/verilog" +incdir+"$ref_dir/../../../../../src/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_scnn_refclk/hdl/verilog" +incdir+"$ref_dir/../../../../../src/bd/system/ip/system_MIPI_CSI_2_RX_0_0_1/hdl/ila_rxclk_lane/hdl/verilog" +incdir+"$ref_dir/../../../../../src/bd/system/ip/system_MIPI_CSI_2_RX_0_0_1/hdl/ila_rxclk/hdl/verilog" +incdir+"$ref_dir/../../../../../src/bd/system/ip/system_MIPI_CSI_2_RX_0_0_1/hdl/ila_vidclk/hdl/verilog" +incdir+"D:/Kits/Ti/beaglebone/Xilinx/Vivado/2017.4/data/xilinx_vip/include" \
    "$ref_dir/../../../../../src/bd/system/ipshared/a16a/hdl/axi_vip_v1_1_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work processing_system7_vip_v1_0_3 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../../src/bd/system/ipshared/f8d8/hdl" +incdir+"$ref_dir/../../../../../src/bd/system/ipshared/4868" +incdir+"$ref_dir/../../../../../src/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../../src/bd/system/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../../../src/bd/system/ipshared/1313/hdl" +incdir+"$ref_dir/../../../../../src/bd/system/ip/system_MIPI_CSI_2_RX_0_0_1/hdl/line_buffer/hdl" +incdir+"$ref_dir/../../../../../src/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_rxclk/hdl/verilog" +incdir+"$ref_dir/../../../../../src/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_refclk/hdl/verilog" +incdir+"$ref_dir/../../../../../src/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_scnn_refclk/hdl/verilog" +incdir+"$ref_dir/../../../../../src/bd/system/ip/system_MIPI_CSI_2_RX_0_0_1/hdl/ila_rxclk_lane/hdl/verilog" +incdir+"$ref_dir/../../../../../src/bd/system/ip/system_MIPI_CSI_2_RX_0_0_1/hdl/ila_rxclk/hdl/verilog" +incdir+"$ref_dir/../../../../../src/bd/system/ip/system_MIPI_CSI_2_RX_0_0_1/hdl/ila_vidclk/hdl/verilog" +incdir+"D:/Kits/Ti/beaglebone/Xilinx/Vivado/2017.4/data/xilinx_vip/include" \
    "$ref_dir/../../../../../src/bd/system/ipshared/1313/hdl/processing_system7_vip_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../../src/bd/system/ipshared/f8d8/hdl" +incdir+"$ref_dir/../../../../../src/bd/system/ipshared/4868" +incdir+"$ref_dir/../../../../../src/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../../src/bd/system/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../../../src/bd/system/ipshared/1313/hdl" +incdir+"$ref_dir/../../../../../src/bd/system/ip/system_MIPI_CSI_2_RX_0_0_1/hdl/line_buffer/hdl" +incdir+"$ref_dir/../../../../../src/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_rxclk/hdl/verilog" +incdir+"$ref_dir/../../../../../src/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_refclk/hdl/verilog" +incdir+"$ref_dir/../../../../../src/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_scnn_refclk/hdl/verilog" +incdir+"$ref_dir/../../../../../src/bd/system/ip/system_MIPI_CSI_2_RX_0_0_1/hdl/ila_rxclk_lane/hdl/verilog" +incdir+"$ref_dir/../../../../../src/bd/system/ip/system_MIPI_CSI_2_RX_0_0_1/hdl/ila_rxclk/hdl/verilog" +incdir+"$ref_dir/../../../../../src/bd/system/ip/system_MIPI_CSI_2_RX_0_0_1/hdl/ila_vidclk/hdl/verilog" +incdir+"D:/Kits/Ti/beaglebone/Xilinx/Vivado/2017.4/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/system/ip/system_processing_system7_0_0/sim/system_processing_system7_0_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../../../src/bd/system/ipshared/20df/src/ClockGen.vhd" \
    "$ref_dir/../../../../../src/bd/system/ipshared/20df/src/SyncAsync.vhd" \
    "$ref_dir/../../../../../src/bd/system/ipshared/20df/src/SyncAsyncReset.vhd" \
    "$ref_dir/../../../../../src/bd/system/ipshared/20df/src/DVI_Constants.vhd" \
    "$ref_dir/../../../../../src/bd/system/ipshared/20df/src/OutputSERDES.vhd" \
    "$ref_dir/../../../../../src/bd/system/ipshared/20df/src/TMDS_Encoder.vhd" \
    "$ref_dir/../../../../../src/bd/system/ipshared/20df/src/rgb2dvi.vhd" \
    "$ref_dir/../../../bd/system/ip/system_rgb2dvi_0_0/sim/system_rgb2dvi_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work proc_sys_reset_v5_0_12 $vhdlan_opts \
    "$ref_dir/../../../../../src/bd/system/ipshared/f86a/hdl/proc_sys_reset_v5_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/system/ip/system_rst_clk_wiz_0_50M_0/sim/system_rst_clk_wiz_0_50M_0.vhd" \
    "$ref_dir/../../../bd/system/ip/system_rst_vid_clk_dyn_0/sim/system_rst_vid_clk_dyn_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_lite_ipif_v3_0_4 $vhdlan_opts \
    "$ref_dir/../../../../../src/bd/system/ipshared/cced/hdl/axi_lite_ipif_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work v_tc_v6_1_12 $vhdlan_opts \
    "$ref_dir/../../../../../src/bd/system/ipshared/6694/hdl/v_tc_v6_1_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work v_vid_in_axi4s_v4_0_7 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../../src/bd/system/ipshared/f8d8/hdl" +incdir+"$ref_dir/../../../../../src/bd/system/ipshared/4868" +incdir+"$ref_dir/../../../../../src/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../../src/bd/system/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../../../src/bd/system/ipshared/1313/hdl" +incdir+"$ref_dir/../../../../../src/bd/system/ip/system_MIPI_CSI_2_RX_0_0_1/hdl/line_buffer/hdl" +incdir+"$ref_dir/../../../../../src/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_rxclk/hdl/verilog" +incdir+"$ref_dir/../../../../../src/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_refclk/hdl/verilog" +incdir+"$ref_dir/../../../../../src/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_scnn_refclk/hdl/verilog" +incdir+"$ref_dir/../../../../../src/bd/system/ip/system_MIPI_CSI_2_RX_0_0_1/hdl/ila_rxclk_lane/hdl/verilog" +incdir+"$ref_dir/../../../../../src/bd/system/ip/system_MIPI_CSI_2_RX_0_0_1/hdl/ila_rxclk/hdl/verilog" +incdir+"$ref_dir/../../../../../src/bd/system/ip/system_MIPI_CSI_2_RX_0_0_1/hdl/ila_vidclk/hdl/verilog" +incdir+"D:/Kits/Ti/beaglebone/Xilinx/Vivado/2017.4/data/xilinx_vip/include" \
    "$ref_dir/../../../../../src/bd/system/ipshared/f931/hdl/v_vid_in_axi4s_v4_0_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work v_axi4s_vid_out_v4_0_8 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../../src/bd/system/ipshared/f8d8/hdl" +incdir+"$ref_dir/../../../../../src/bd/system/ipshared/4868" +incdir+"$ref_dir/../../../../../src/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../../src/bd/system/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../../../src/bd/system/ipshared/1313/hdl" +incdir+"$ref_dir/../../../../../src/bd/system/ip/system_MIPI_CSI_2_RX_0_0_1/hdl/line_buffer/hdl" +incdir+"$ref_dir/../../../../../src/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_rxclk/hdl/verilog" +incdir+"$ref_dir/../../../../../src/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_refclk/hdl/verilog" +incdir+"$ref_dir/../../../../../src/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_scnn_refclk/hdl/verilog" +incdir+"$ref_dir/../../../../../src/bd/system/ip/system_MIPI_CSI_2_RX_0_0_1/hdl/ila_rxclk_lane/hdl/verilog" +incdir+"$ref_dir/../../../../../src/bd/system/ip/system_MIPI_CSI_2_RX_0_0_1/hdl/ila_rxclk/hdl/verilog" +incdir+"$ref_dir/../../../../../src/bd/system/ip/system_MIPI_CSI_2_RX_0_0_1/hdl/ila_vidclk/hdl/verilog" +incdir+"D:/Kits/Ti/beaglebone/Xilinx/Vivado/2017.4/data/xilinx_vip/include" \
    "$ref_dir/../../../../../src/bd/system/ipshared/fc47/hdl/v_axi4s_vid_out_v4_0_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../../src/bd/system/ipshared/f8d8/hdl" +incdir+"$ref_dir/../../../../../src/bd/system/ipshared/4868" +incdir+"$ref_dir/../../../../../src/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../../src/bd/system/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../../../src/bd/system/ipshared/1313/hdl" +incdir+"$ref_dir/../../../../../src/bd/system/ip/system_MIPI_CSI_2_RX_0_0_1/hdl/line_buffer/hdl" +incdir+"$ref_dir/../../../../../src/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_rxclk/hdl/verilog" +incdir+"$ref_dir/../../../../../src/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_refclk/hdl/verilog" +incdir+"$ref_dir/../../../../../src/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_scnn_refclk/hdl/verilog" +incdir+"$ref_dir/../../../../../src/bd/system/ip/system_MIPI_CSI_2_RX_0_0_1/hdl/ila_rxclk_lane/hdl/verilog" +incdir+"$ref_dir/../../../../../src/bd/system/ip/system_MIPI_CSI_2_RX_0_0_1/hdl/ila_rxclk/hdl/verilog" +incdir+"$ref_dir/../../../../../src/bd/system/ip/system_MIPI_CSI_2_RX_0_0_1/hdl/ila_vidclk/hdl/verilog" +incdir+"D:/Kits/Ti/beaglebone/Xilinx/Vivado/2017.4/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/system/ip/system_v_axi4s_vid_out_0_0/sim/system_v_axi4s_vid_out_0_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/system/ip/system_vtg_0/sim/system_vtg_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xlconcat_v2_1_1 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../../src/bd/system/ipshared/f8d8/hdl" +incdir+"$ref_dir/../../../../../src/bd/system/ipshared/4868" +incdir+"$ref_dir/../../../../../src/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../../src/bd/system/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../../../src/bd/system/ipshared/1313/hdl" +incdir+"$ref_dir/../../../../../src/bd/system/ip/system_MIPI_CSI_2_RX_0_0_1/hdl/line_buffer/hdl" +incdir+"$ref_dir/../../../../../src/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_rxclk/hdl/verilog" +incdir+"$ref_dir/../../../../../src/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_refclk/hdl/verilog" +incdir+"$ref_dir/../../../../../src/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_scnn_refclk/hdl/verilog" +incdir+"$ref_dir/../../../../../src/bd/system/ip/system_MIPI_CSI_2_RX_0_0_1/hdl/ila_rxclk_lane/hdl/verilog" +incdir+"$ref_dir/../../../../../src/bd/system/ip/system_MIPI_CSI_2_RX_0_0_1/hdl/ila_rxclk/hdl/verilog" +incdir+"$ref_dir/../../../../../src/bd/system/ip/system_MIPI_CSI_2_RX_0_0_1/hdl/ila_vidclk/hdl/verilog" +incdir+"D:/Kits/Ti/beaglebone/Xilinx/Vivado/2017.4/data/xilinx_vip/include" \
    "$ref_dir/../../../../../src/bd/system/ipshared/2f66/hdl/xlconcat_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../../src/bd/system/ipshared/f8d8/hdl" +incdir+"$ref_dir/../../../../../src/bd/system/ipshared/4868" +incdir+"$ref_dir/../../../../../src/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../../src/bd/system/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../../../src/bd/system/ipshared/1313/hdl" +incdir+"$ref_dir/../../../../../src/bd/system/ip/system_MIPI_CSI_2_RX_0_0_1/hdl/line_buffer/hdl" +incdir+"$ref_dir/../../../../../src/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_rxclk/hdl/verilog" +incdir+"$ref_dir/../../../../../src/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_refclk/hdl/verilog" +incdir+"$ref_dir/../../../../../src/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_scnn_refclk/hdl/verilog" +incdir+"$ref_dir/../../../../../src/bd/system/ip/system_MIPI_CSI_2_RX_0_0_1/hdl/ila_rxclk_lane/hdl/verilog" +incdir+"$ref_dir/../../../../../src/bd/system/ip/system_MIPI_CSI_2_RX_0_0_1/hdl/ila_rxclk/hdl/verilog" +incdir+"$ref_dir/../../../../../src/bd/system/ip/system_MIPI_CSI_2_RX_0_0_1/hdl/ila_vidclk/hdl/verilog" +incdir+"D:/Kits/Ti/beaglebone/Xilinx/Vivado/2017.4/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/system/ip/system_xlconcat_0_0/sim/system_xlconcat_0_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/system/ip/system_DVIClocking_0_0/sim/system_DVIClocking_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../../src/bd/system/ipshared/f8d8/hdl" +incdir+"$ref_dir/../../../../../src/bd/system/ipshared/4868" +incdir+"$ref_dir/../../../../../src/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../../src/bd/system/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../../../src/bd/system/ipshared/1313/hdl" +incdir+"$ref_dir/../../../../../src/bd/system/ip/system_MIPI_CSI_2_RX_0_0_1/hdl/line_buffer/hdl" +incdir+"$ref_dir/../../../../../src/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_rxclk/hdl/verilog" +incdir+"$ref_dir/../../../../../src/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_refclk/hdl/verilog" +incdir+"$ref_dir/../../../../../src/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_scnn_refclk/hdl/verilog" +incdir+"$ref_dir/../../../../../src/bd/system/ip/system_MIPI_CSI_2_RX_0_0_1/hdl/ila_rxclk_lane/hdl/verilog" +incdir+"$ref_dir/../../../../../src/bd/system/ip/system_MIPI_CSI_2_RX_0_0_1/hdl/ila_rxclk/hdl/verilog" +incdir+"$ref_dir/../../../../../src/bd/system/ip/system_MIPI_CSI_2_RX_0_0_1/hdl/ila_vidclk/hdl/verilog" +incdir+"D:/Kits/Ti/beaglebone/Xilinx/Vivado/2017.4/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/system/ip/system_video_dynclk_1/system_video_dynclk_1_mmcm_pll_drp.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/system/ip/system_video_dynclk_1/proc_common_v3_00_a/hdl/src/vhdl/system_video_dynclk_1_conv_funs_pkg.vhd" \
    "$ref_dir/../../../bd/system/ip/system_video_dynclk_1/proc_common_v3_00_a/hdl/src/vhdl/system_video_dynclk_1_proc_common_pkg.vhd" \
    "$ref_dir/../../../bd/system/ip/system_video_dynclk_1/proc_common_v3_00_a/hdl/src/vhdl/system_video_dynclk_1_ipif_pkg.vhd" \
    "$ref_dir/../../../bd/system/ip/system_video_dynclk_1/proc_common_v3_00_a/hdl/src/vhdl/system_video_dynclk_1_family_support.vhd" \
    "$ref_dir/../../../bd/system/ip/system_video_dynclk_1/proc_common_v3_00_a/hdl/src/vhdl/system_video_dynclk_1_family.vhd" \
    "$ref_dir/../../../bd/system/ip/system_video_dynclk_1/proc_common_v3_00_a/hdl/src/vhdl/system_video_dynclk_1_soft_reset.vhd" \
    "$ref_dir/../../../bd/system/ip/system_video_dynclk_1/proc_common_v3_00_a/hdl/src/vhdl/system_video_dynclk_1_pselect_f.vhd" \
    "$ref_dir/../../../bd/system/ip/system_video_dynclk_1/axi_lite_ipif_v1_01_a/hdl/src/vhdl/system_video_dynclk_1_address_decoder.vhd" \
    "$ref_dir/../../../bd/system/ip/system_video_dynclk_1/axi_lite_ipif_v1_01_a/hdl/src/vhdl/system_video_dynclk_1_slave_attachment.vhd" \
    "$ref_dir/../../../bd/system/ip/system_video_dynclk_1/axi_lite_ipif_v1_01_a/hdl/src/vhdl/system_video_dynclk_1_axi_lite_ipif.vhd" \
    "$ref_dir/../../../bd/system/ip/system_video_dynclk_1/system_video_dynclk_1_clk_wiz_drp.vhd" \
    "$ref_dir/../../../bd/system/ip/system_video_dynclk_1/system_video_dynclk_1_axi_clk_config.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../../src/bd/system/ipshared/f8d8/hdl" +incdir+"$ref_dir/../../../../../src/bd/system/ipshared/4868" +incdir+"$ref_dir/../../../../../src/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../../src/bd/system/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../../../src/bd/system/ipshared/1313/hdl" +incdir+"$ref_dir/../../../../../src/bd/system/ip/system_MIPI_CSI_2_RX_0_0_1/hdl/line_buffer/hdl" +incdir+"$ref_dir/../../../../../src/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_rxclk/hdl/verilog" +incdir+"$ref_dir/../../../../../src/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_refclk/hdl/verilog" +incdir+"$ref_dir/../../../../../src/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_scnn_refclk/hdl/verilog" +incdir+"$ref_dir/../../../../../src/bd/system/ip/system_MIPI_CSI_2_RX_0_0_1/hdl/ila_rxclk_lane/hdl/verilog" +incdir+"$ref_dir/../../../../../src/bd/system/ip/system_MIPI_CSI_2_RX_0_0_1/hdl/ila_rxclk/hdl/verilog" +incdir+"$ref_dir/../../../../../src/bd/system/ip/system_MIPI_CSI_2_RX_0_0_1/hdl/ila_vidclk/hdl/verilog" +incdir+"D:/Kits/Ti/beaglebone/Xilinx/Vivado/2017.4/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/system/ip/system_video_dynclk_1/system_video_dynclk_1_clk_wiz.v" \
    "$ref_dir/../../../bd/system/ip/system_video_dynclk_1/system_video_dynclk_1.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work generic_baseblocks_v2_1_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../../src/bd/system/ipshared/f8d8/hdl" +incdir+"$ref_dir/../../../../../src/bd/system/ipshared/4868" +incdir+"$ref_dir/../../../../../src/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../../src/bd/system/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../../../src/bd/system/ipshared/1313/hdl" +incdir+"$ref_dir/../../../../../src/bd/system/ip/system_MIPI_CSI_2_RX_0_0_1/hdl/line_buffer/hdl" +incdir+"$ref_dir/../../../../../src/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_rxclk/hdl/verilog" +incdir+"$ref_dir/../../../../../src/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_refclk/hdl/verilog" +incdir+"$ref_dir/../../../../../src/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_scnn_refclk/hdl/verilog" +incdir+"$ref_dir/../../../../../src/bd/system/ip/system_MIPI_CSI_2_RX_0_0_1/hdl/ila_rxclk_lane/hdl/verilog" +incdir+"$ref_dir/../../../../../src/bd/system/ip/system_MIPI_CSI_2_RX_0_0_1/hdl/ila_rxclk/hdl/verilog" +incdir+"$ref_dir/../../../../../src/bd/system/ip/system_MIPI_CSI_2_RX_0_0_1/hdl/ila_vidclk/hdl/verilog" +incdir+"D:/Kits/Ti/beaglebone/Xilinx/Vivado/2017.4/data/xilinx_vip/include" \
    "$ref_dir/../../../../../src/bd/system/ipshared/b752/hdl/generic_baseblocks_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_register_slice_v2_1_15 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../../src/bd/system/ipshared/f8d8/hdl" +incdir+"$ref_dir/../../../../../src/bd/system/ipshared/4868" +incdir+"$ref_dir/../../../../../src/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../../src/bd/system/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../../../src/bd/system/ipshared/1313/hdl" +incdir+"$ref_dir/../../../../../src/bd/system/ip/system_MIPI_CSI_2_RX_0_0_1/hdl/line_buffer/hdl" +incdir+"$ref_dir/../../../../../src/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_rxclk/hdl/verilog" +incdir+"$ref_dir/../../../../../src/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_refclk/hdl/verilog" +incdir+"$ref_dir/../../../../../src/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_scnn_refclk/hdl/verilog" +incdir+"$ref_dir/../../../../../src/bd/system/ip/system_MIPI_CSI_2_RX_0_0_1/hdl/ila_rxclk_lane/hdl/verilog" +incdir+"$ref_dir/../../../../../src/bd/system/ip/system_MIPI_CSI_2_RX_0_0_1/hdl/ila_rxclk/hdl/verilog" +incdir+"$ref_dir/../../../../../src/bd/system/ip/system_MIPI_CSI_2_RX_0_0_1/hdl/ila_vidclk/hdl/verilog" +incdir+"D:/Kits/Ti/beaglebone/Xilinx/Vivado/2017.4/data/xilinx_vip/include" \
    "$ref_dir/../../../../../src/bd/system/ipshared/3ed1/hdl/axi_register_slice_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_data_fifo_v2_1_14 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../../src/bd/system/ipshared/f8d8/hdl" +incdir+"$ref_dir/../../../../../src/bd/system/ipshared/4868" +incdir+"$ref_dir/../../../../../src/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../../src/bd/system/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../../../src/bd/system/ipshared/1313/hdl" +incdir+"$ref_dir/../../../../../src/bd/system/ip/system_MIPI_CSI_2_RX_0_0_1/hdl/line_buffer/hdl" +incdir+"$ref_dir/../../../../../src/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_rxclk/hdl/verilog" +incdir+"$ref_dir/../../../../../src/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_refclk/hdl/verilog" +incdir+"$ref_dir/../../../../../src/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_scnn_refclk/hdl/verilog" +incdir+"$ref_dir/../../../../../src/bd/system/ip/system_MIPI_CSI_2_RX_0_0_1/hdl/ila_rxclk_lane/hdl/verilog" +incdir+"$ref_dir/../../../../../src/bd/system/ip/system_MIPI_CSI_2_RX_0_0_1/hdl/ila_rxclk/hdl/verilog" +incdir+"$ref_dir/../../../../../src/bd/system/ip/system_MIPI_CSI_2_RX_0_0_1/hdl/ila_vidclk/hdl/verilog" +incdir+"D:/Kits/Ti/beaglebone/Xilinx/Vivado/2017.4/data/xilinx_vip/include" \
    "$ref_dir/../../../../../src/bd/system/ipshared/9909/hdl/axi_data_fifo_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_crossbar_v2_1_16 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../../src/bd/system/ipshared/f8d8/hdl" +incdir+"$ref_dir/../../../../../src/bd/system/ipshared/4868" +incdir+"$ref_dir/../../../../../src/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../../src/bd/system/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../../../src/bd/system/ipshared/1313/hdl" +incdir+"$ref_dir/../../../../../src/bd/system/ip/system_MIPI_CSI_2_RX_0_0_1/hdl/line_buffer/hdl" +incdir+"$ref_dir/../../../../../src/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_rxclk/hdl/verilog" +incdir+"$ref_dir/../../../../../src/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_refclk/hdl/verilog" +incdir+"$ref_dir/../../../../../src/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_scnn_refclk/hdl/verilog" +incdir+"$ref_dir/../../../../../src/bd/system/ip/system_MIPI_CSI_2_RX_0_0_1/hdl/ila_rxclk_lane/hdl/verilog" +incdir+"$ref_dir/../../../../../src/bd/system/ip/system_MIPI_CSI_2_RX_0_0_1/hdl/ila_rxclk/hdl/verilog" +incdir+"$ref_dir/../../../../../src/bd/system/ip/system_MIPI_CSI_2_RX_0_0_1/hdl/ila_vidclk/hdl/verilog" +incdir+"D:/Kits/Ti/beaglebone/Xilinx/Vivado/2017.4/data/xilinx_vip/include" \
    "$ref_dir/../../../../../src/bd/system/ipshared/c631/hdl/axi_crossbar_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../../src/bd/system/ipshared/f8d8/hdl" +incdir+"$ref_dir/../../../../../src/bd/system/ipshared/4868" +incdir+"$ref_dir/../../../../../src/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../../src/bd/system/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../../../src/bd/system/ipshared/1313/hdl" +incdir+"$ref_dir/../../../../../src/bd/system/ip/system_MIPI_CSI_2_RX_0_0_1/hdl/line_buffer/hdl" +incdir+"$ref_dir/../../../../../src/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_rxclk/hdl/verilog" +incdir+"$ref_dir/../../../../../src/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_refclk/hdl/verilog" +incdir+"$ref_dir/../../../../../src/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_scnn_refclk/hdl/verilog" +incdir+"$ref_dir/../../../../../src/bd/system/ip/system_MIPI_CSI_2_RX_0_0_1/hdl/ila_rxclk_lane/hdl/verilog" +incdir+"$ref_dir/../../../../../src/bd/system/ip/system_MIPI_CSI_2_RX_0_0_1/hdl/ila_rxclk/hdl/verilog" +incdir+"$ref_dir/../../../../../src/bd/system/ip/system_MIPI_CSI_2_RX_0_0_1/hdl/ila_vidclk/hdl/verilog" +incdir+"D:/Kits/Ti/beaglebone/Xilinx/Vivado/2017.4/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/system/ip/system_xbar_0/sim/system_xbar_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/system/sim/system.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work axis_infrastructure_v1_1_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../../src/bd/system/ipshared/f8d8/hdl" +incdir+"$ref_dir/../../../../../src/bd/system/ipshared/4868" +incdir+"$ref_dir/../../../../../src/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../../src/bd/system/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../../../src/bd/system/ipshared/1313/hdl" +incdir+"$ref_dir/../../../../../src/bd/system/ip/system_MIPI_CSI_2_RX_0_0_1/hdl/line_buffer/hdl" +incdir+"$ref_dir/../../../../../src/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_rxclk/hdl/verilog" +incdir+"$ref_dir/../../../../../src/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_refclk/hdl/verilog" +incdir+"$ref_dir/../../../../../src/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_scnn_refclk/hdl/verilog" +incdir+"$ref_dir/../../../../../src/bd/system/ip/system_MIPI_CSI_2_RX_0_0_1/hdl/ila_rxclk_lane/hdl/verilog" +incdir+"$ref_dir/../../../../../src/bd/system/ip/system_MIPI_CSI_2_RX_0_0_1/hdl/ila_rxclk/hdl/verilog" +incdir+"$ref_dir/../../../../../src/bd/system/ip/system_MIPI_CSI_2_RX_0_0_1/hdl/ila_vidclk/hdl/verilog" +incdir+"D:/Kits/Ti/beaglebone/Xilinx/Vivado/2017.4/data/xilinx_vip/include" \
    "$ref_dir/../../../../../src/bd/system/ip/system_MIPI_CSI_2_RX_0_0_1/hdl/line_buffer/hdl/axis_infrastructure_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axis_data_fifo_v1_1_16 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../../src/bd/system/ipshared/f8d8/hdl" +incdir+"$ref_dir/../../../../../src/bd/system/ipshared/4868" +incdir+"$ref_dir/../../../../../src/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../../src/bd/system/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../../../src/bd/system/ipshared/1313/hdl" +incdir+"$ref_dir/../../../../../src/bd/system/ip/system_MIPI_CSI_2_RX_0_0_1/hdl/line_buffer/hdl" +incdir+"$ref_dir/../../../../../src/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_rxclk/hdl/verilog" +incdir+"$ref_dir/../../../../../src/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_refclk/hdl/verilog" +incdir+"$ref_dir/../../../../../src/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_scnn_refclk/hdl/verilog" +incdir+"$ref_dir/../../../../../src/bd/system/ip/system_MIPI_CSI_2_RX_0_0_1/hdl/ila_rxclk_lane/hdl/verilog" +incdir+"$ref_dir/../../../../../src/bd/system/ip/system_MIPI_CSI_2_RX_0_0_1/hdl/ila_rxclk/hdl/verilog" +incdir+"$ref_dir/../../../../../src/bd/system/ip/system_MIPI_CSI_2_RX_0_0_1/hdl/ila_vidclk/hdl/verilog" +incdir+"D:/Kits/Ti/beaglebone/Xilinx/Vivado/2017.4/data/xilinx_vip/include" \
    "$ref_dir/../../../../../src/bd/system/ip/system_MIPI_CSI_2_RX_0_0_1/hdl/line_buffer/hdl/axis_data_fifo_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../../src/bd/system/ipshared/f8d8/hdl" +incdir+"$ref_dir/../../../../../src/bd/system/ipshared/4868" +incdir+"$ref_dir/../../../../../src/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../../src/bd/system/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../../../src/bd/system/ipshared/1313/hdl" +incdir+"$ref_dir/../../../../../src/bd/system/ip/system_MIPI_CSI_2_RX_0_0_1/hdl/line_buffer/hdl" +incdir+"$ref_dir/../../../../../src/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_rxclk/hdl/verilog" +incdir+"$ref_dir/../../../../../src/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_refclk/hdl/verilog" +incdir+"$ref_dir/../../../../../src/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_scnn_refclk/hdl/verilog" +incdir+"$ref_dir/../../../../../src/bd/system/ip/system_MIPI_CSI_2_RX_0_0_1/hdl/ila_rxclk_lane/hdl/verilog" +incdir+"$ref_dir/../../../../../src/bd/system/ip/system_MIPI_CSI_2_RX_0_0_1/hdl/ila_rxclk/hdl/verilog" +incdir+"$ref_dir/../../../../../src/bd/system/ip/system_MIPI_CSI_2_RX_0_0_1/hdl/ila_vidclk/hdl/verilog" +incdir+"D:/Kits/Ti/beaglebone/Xilinx/Vivado/2017.4/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/system/ip/system_MIPI_CSI_2_RX_0_0_1/hdl/line_buffer/sim/line_buffer.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/system/ip/system_MIPI_CSI_2_RX_0_0_1/hdl/ila_rxclk_lane/sim/ila_rxclk_lane.vhd" \
    "$ref_dir/../../../bd/system/ip/system_MIPI_CSI_2_RX_0_0_1/hdl/ila_rxclk/sim/ila_rxclk.vhd" \
    "$ref_dir/../../../bd/system/ip/system_MIPI_CSI_2_RX_0_0_1/hdl/ila_vidclk/sim/ila_vidclk.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../../src/bd/system/ipshared/f8d8/hdl" +incdir+"$ref_dir/../../../../../src/bd/system/ipshared/4868" +incdir+"$ref_dir/../../../../../src/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../../src/bd/system/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../../../src/bd/system/ipshared/1313/hdl" +incdir+"$ref_dir/../../../../../src/bd/system/ip/system_MIPI_CSI_2_RX_0_0_1/hdl/line_buffer/hdl" +incdir+"$ref_dir/../../../../../src/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_rxclk/hdl/verilog" +incdir+"$ref_dir/../../../../../src/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_refclk/hdl/verilog" +incdir+"$ref_dir/../../../../../src/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_scnn_refclk/hdl/verilog" +incdir+"$ref_dir/../../../../../src/bd/system/ip/system_MIPI_CSI_2_RX_0_0_1/hdl/ila_rxclk_lane/hdl/verilog" +incdir+"$ref_dir/../../../../../src/bd/system/ip/system_MIPI_CSI_2_RX_0_0_1/hdl/ila_rxclk/hdl/verilog" +incdir+"$ref_dir/../../../../../src/bd/system/ip/system_MIPI_CSI_2_RX_0_0_1/hdl/ila_vidclk/hdl/verilog" +incdir+"D:/Kits/Ti/beaglebone/Xilinx/Vivado/2017.4/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/system/ip/system_MIPI_CSI_2_RX_0_0_1/hdl/cdc_fifo/sim/cdc_fifo.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/system/ipshared/af9b/hdl/SimpleFIFO.vhd" \
    "$ref_dir/../../../bd/system/ipshared/af9b/hdl/CRC16_behavioral.vhd" \
    "$ref_dir/../../../bd/system/ipshared/af9b/hdl/ECC.vhd" \
    "$ref_dir/../../../bd/system/ipshared/af9b/hdl/DebugLib.vhd" \
    "$ref_dir/../../../bd/system/ipshared/af9b/hdl/LM.vhd" \
    "$ref_dir/../../../bd/system/ipshared/af9b/hdl/LLP.vhd" \
    "$ref_dir/../../../bd/system/ipshared/af9b/hdl/MIPI_CSI_2_RX_v1_0_S_AXI_LITE.vhd" \
    "$ref_dir/../../../bd/system/ipshared/af9b/hdl/MIPI_CSI2_Rx.vhd" \
    "$ref_dir/../../../bd/system/ipshared/af9b/hdl/MIPI_CSI2_RxTop.vhd" \
    "$ref_dir/../../../bd/system/ip/system_MIPI_CSI_2_RX_0_0_1/sim/system_MIPI_CSI_2_RX_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work axi_protocol_converter_v2_1_15 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../../src/bd/system/ipshared/f8d8/hdl" +incdir+"$ref_dir/../../../../../src/bd/system/ipshared/4868" +incdir+"$ref_dir/../../../../../src/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../../src/bd/system/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../../../src/bd/system/ipshared/1313/hdl" +incdir+"$ref_dir/../../../../../src/bd/system/ip/system_MIPI_CSI_2_RX_0_0_1/hdl/line_buffer/hdl" +incdir+"$ref_dir/../../../../../src/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_rxclk/hdl/verilog" +incdir+"$ref_dir/../../../../../src/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_refclk/hdl/verilog" +incdir+"$ref_dir/../../../../../src/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_scnn_refclk/hdl/verilog" +incdir+"$ref_dir/../../../../../src/bd/system/ip/system_MIPI_CSI_2_RX_0_0_1/hdl/ila_rxclk_lane/hdl/verilog" +incdir+"$ref_dir/../../../../../src/bd/system/ip/system_MIPI_CSI_2_RX_0_0_1/hdl/ila_rxclk/hdl/verilog" +incdir+"$ref_dir/../../../../../src/bd/system/ip/system_MIPI_CSI_2_RX_0_0_1/hdl/ila_vidclk/hdl/verilog" +incdir+"D:/Kits/Ti/beaglebone/Xilinx/Vivado/2017.4/data/xilinx_vip/include" \
    "$ref_dir/../../../../../src/bd/system/ipshared/ff69/hdl/axi_protocol_converter_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../../src/bd/system/ipshared/f8d8/hdl" +incdir+"$ref_dir/../../../../../src/bd/system/ipshared/4868" +incdir+"$ref_dir/../../../../../src/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../../src/bd/system/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../../../src/bd/system/ipshared/1313/hdl" +incdir+"$ref_dir/../../../../../src/bd/system/ip/system_MIPI_CSI_2_RX_0_0_1/hdl/line_buffer/hdl" +incdir+"$ref_dir/../../../../../src/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_rxclk/hdl/verilog" +incdir+"$ref_dir/../../../../../src/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_refclk/hdl/verilog" +incdir+"$ref_dir/../../../../../src/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_scnn_refclk/hdl/verilog" +incdir+"$ref_dir/../../../../../src/bd/system/ip/system_MIPI_CSI_2_RX_0_0_1/hdl/ila_rxclk_lane/hdl/verilog" +incdir+"$ref_dir/../../../../../src/bd/system/ip/system_MIPI_CSI_2_RX_0_0_1/hdl/ila_rxclk/hdl/verilog" +incdir+"$ref_dir/../../../../../src/bd/system/ip/system_MIPI_CSI_2_RX_0_0_1/hdl/ila_vidclk/hdl/verilog" +incdir+"D:/Kits/Ti/beaglebone/Xilinx/Vivado/2017.4/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/system/ip/system_auto_pc_2/sim/system_auto_pc_2.v" \
    "$ref_dir/../../../bd/system/ip/system_auto_pc_1/sim/system_auto_pc_1.v" \
    "$ref_dir/../../../bd/system/ip/system_auto_pc_0/sim/system_auto_pc_0.v" \
  2>&1 | tee -a vlogan.log


  vlogan -work xil_defaultlib $vlogan_opts +v2k \
    glbl.v \
  2>&1 | tee -a vlogan.log

}

# RUN_STEP: <elaborate>
elaborate()
{
  vcs $vcs_elab_opts xil_defaultlib.system xil_defaultlib.glbl -o system_simv
}

# RUN_STEP: <simulate>
simulate()
{
  ./system_simv $vcs_sim_opts -do simulate.do
}

# STEP: setup
setup()
{
  case $1 in
    "-lib_map_path" )
      if [[ ($2 == "") ]]; then
        echo -e "ERROR: Simulation library directory path not specified (type \"./system.sh -help\" for more information)\n"
        exit 1
      fi
      create_lib_mappings $2
    ;;
    "-reset_run" )
      reset_run
      echo -e "INFO: Simulation run files deleted.\n"
      exit 0
    ;;
    "-noclean_files" )
      # do not remove previous data
    ;;
    * )
      create_lib_mappings $2
  esac

  create_lib_dir

  # Add any setup/initialization commands here:-

  # <user specific commands>

}

# Define design library mappings
create_lib_mappings()
{
  file="synopsys_sim.setup"
  if [[ -e $file ]]; then
    if [[ ($1 == "") ]]; then
      return
    else
      rm -rf $file
    fi
  fi

  touch $file

  lib_map_path=""
  if [[ ($1 != "") ]]; then
    lib_map_path="$1"
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    mapping="$lib:$sim_lib_dir/$lib"
    echo $mapping >> $file
  done

  if [[ ($lib_map_path != "") ]]; then
    incl_ref="OTHERS=$lib_map_path/synopsys_sim.setup"
    echo $incl_ref >> $file
  fi
}

# Create design library directory paths
create_lib_dir()
{
  if [[ -e $sim_lib_dir ]]; then
    rm -rf $sim_lib_dir
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    lib_dir="$sim_lib_dir/$lib"
    if [[ ! -e $lib_dir ]]; then
      mkdir -p $lib_dir
    fi
  done
}

# Delete generated data from the previous run
reset_run()
{
  files_to_remove=(ucli.key system_simv vlogan.log vhdlan.log compile.log elaborate.log simulate.log .vlogansetup.env .vlogansetup.args .vcs_lib_lock scirocco_command.log 64 AN.DB csrc system_simv.daidir)
  for (( i=0; i<${#files_to_remove[*]}; i++ )); do
    file="${files_to_remove[i]}"
    if [[ -e $file ]]; then
      rm -rf $file
    fi
  done

  create_lib_dir
}

# Check command line arguments
check_args()
{
  if [[ ($1 == 1 ) && ($2 != "-lib_map_path" && $2 != "-noclean_files" && $2 != "-reset_run" && $2 != "-help" && $2 != "-h") ]]; then
    echo -e "ERROR: Unknown option specified '$2' (type \"./system.sh -help\" for more information)\n"
    exit 1
  fi

  if [[ ($2 == "-help" || $2 == "-h") ]]; then
    usage
  fi
}

# Script usage
usage()
{
  msg="Usage: system.sh [-help]\n\
Usage: system.sh [-lib_map_path]\n\
Usage: system.sh [-reset_run]\n\
Usage: system.sh [-noclean_files]\n\n\
[-help] -- Print help information for this script\n\n\
[-lib_map_path <path>] -- Compiled simulation library directory path. The simulation library is compiled\n\
using the compile_simlib tcl command. Please see 'compile_simlib -help' for more information.\n\n\
[-reset_run] -- Recreate simulator setup files and library mappings for a clean run. The generated files\n\
from the previous run will be removed. If you don't want to remove the simulator generated files, use the\n\
-noclean_files switch.\n\n\
[-noclean_files] -- Reset previous run, but do not remove simulator generated files from the previous run.\n\n"
  echo -e $msg
  exit 1
}

# Launch script
run $1 $2
